# Generated by Django 5.1.3 on 2024-11-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotsettings', '0001_initial'),
        ('users', '0004_alter_businessuserdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='preferred_chatbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbotsettings.chatbotsettings'),
        ),
        migrations.DeleteModel(
            name='BusinessUserData',
        ),
        migrations.DeleteModel(
            name='ChatBotSettings',
        ),
    ]
