# Generated by Django 5.1.3 on 2024-12-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.CharField(blank=True, max_length=255)),
                ('schema', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
