# Generated by Django 5.1.3 on 2024-12-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loganalyzer',
            name='advice',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='loganalyzer',
            name='chunk',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='loganalyzer',
            name='schema',
            field=models.CharField(blank=True),
        ),
    ]
