# Generated by Django 5.1.3 on 2025-01-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_loganalyzer_advice_alter_loganalyzer_chunk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loganalyzer',
            old_name='advice',
            new_name='log_level',
        ),
        migrations.RemoveField(
            model_name='loganalyzer',
            name='schema',
        ),
    ]
