version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./gunicorn:/run/gunicorn
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:1.26.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Custom config
      - ./nginx/certs:/etc/nginx/certs  # SSL certificates
      - ./nginx/logs:/var/log/nginx  # Logging
    depends_on:
      - web
    networks:
      - app_network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: creditizens
      POSTGRES_PASSWORD: metaverse
      POSTGRES_DB: chatbotaidb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
