# Generated by Django 5.1.3 on 2024-11-26 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('tone', models.CharField(blank=True, max_length=40)),
                ('descritpion', models.CharField(blank=True, max_length=40)),
                ('expertise', models.CharField(blank=True, max_length=40)),
                ('custom_greeting', models.CharField(blank=True, max_length=40)),
                ('example_of_reponse', models.CharField(blank=True, max_length=40)),
                ('origin', models.CharField(blank=True, max_length=40)),
                ('age', models.IntegerField(default=18)),
                ('dream', models.CharField(blank=True, max_length=40)),
                ('avatar', models.ImageField(blank=True, max_length=255, upload_to='uploads/chatbotsettings/')),
                ('business_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
