# Generated by Django 5.1.3 on 2024-11-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotsettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='descritpion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='example_of_reponse',
            new_name='example_of_response',
        ),
    ]
