# Generated by Django 5.1.3 on 2024-12-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdata', '0002_alter_businessuserdata_uuid'),
        ('chatbotsettings', '0003_chatbotsettings_business_user_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotsettings',
            name='business_user_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='businessdata.businessuserdata', to_field='uuid'),
        ),
    ]
