# Generated by Django 5.1.3 on 2024-11-27 18:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuserdata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
