name: Django ChatBotAI Test CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python (Match Local Version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install System Dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3.12-dev libpq-dev libjpeg-dev zlib1g-dev cargo rustc

      # Step 4: Install Python Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Build Rust Library with Maturin
      - name: Build Rust PyO3 library
        run: |
          pip install maturin
          cd rust_lib
          maturin develop

      # Step 6: Wait for PostgreSQL to be Ready
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      # Step 7: Run Migrations
      - name: Run migrations
        env:
          DBNAME: test_db
          DBUSER: postgres
          DBPASSWORD: postgres
          DBHOST: localhost
          DBPORT: 5432
        run: |
          python manage.py migrate

      # Step 8: Run Tests with Coverage
      - name: Run tests with coverage
        env:
          DBNAME: test_db
          DBUSER: postgres
          DBPASSWORD: postgres
          DBHOST: localhost
          DBPORT: 5432
        run: |
          coverage run --source='.' -m pytest --ds=chatbotAI.settings

      # Step 9: Generate and Upload Coverage Report
      - name: Generate coverage report
        run: |
          coverage report
          coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov
